.TH FIZMO-JSON 6 "February 5, 2018" "0.0.1"
.SH NAME
fizmo-json
- JSON-frontend for the fizmo Z-Machine Interpreter.

.SH SYNOPSIS
.B fizmo-json
[ options ]
.I storyfile

.SH DESCRIPTION
.B fizmo-json
is a JSON-based front-end for the fizmo Z-Machine
interpreter\[em]\[lq]\fBF\fPimzo \fBi\fPnterprets \fBZ\fP-\fBm\fPachine
\fBo\fPpcodes\[rq]. Thus, it provides no real user interface of its own, but
instead acts as a wrapper for the input and output. It is designed to be used
for bots or web services.

.SH OPTIONS
The options need to be documented. The only requirement is to have the filename
of the Z-Machine file to run.

.SH SEE ALSO
.BR fizmo-sdl2(6),
.BR fizmo-ncursesw(6),
.BR fizmo-console(6),
.BR frotz(6),
.BR xzip(6),
.BR jzip(6),
.BR inform(1)

.SH AUTHOR
The fizmo-json frontend was written in 2018 by Jared Reisinger.

.SH BUGS
This frontend is in alpha stage and will probably still contain some bugs.
Any feedback to https://github.com/JaredReisinger/fizmo-json/issues is greatly
appreciated.
